#include "cube.h"

#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint16_t permutation_turn[CUBE_FACES][CUBE_PERMUTATIONS];
static uint16_t orientation_turn[CUBE_FACES][CUBE_ORIENTATIONS];
static uint8_t permutation_pdb[CUBE_PERMUTATIONS];
static uint8_t orientation_pdb[CUBE_ORIENTATIONS];

static void build_quarter_turn_tables(void)
{
    uint16_t rank;

    for (rank = 0; rank < CUBE_PERMUTATIONS; ++rank) {
        cube_state_t state;
        uint8_t face;
        cube_unrank_permutation(rank, &state);
        for (face = 0; face < CUBE_FACES; ++face) {
            cube_state_t next = cube_quarter_turn(state, face);
            permutation_turn[face][rank] = cube_rank_permutation(&next);
        }
    }

    for (rank = 0; rank < CUBE_ORIENTATIONS; ++rank) {
        cube_state_t state;
        uint8_t face;
        cube_unrank_orientation(rank, &state);
        for (face = 0; face < CUBE_FACES; ++face) {
            cube_state_t next = cube_quarter_turn(state, face);
            orientation_turn[face][rank] = cube_rank_orientation(&next);
        }
    }
}

static void build_permutation_pdb(void)
{
    uint16_t queue[CUBE_PERMUTATIONS];
    uint16_t head = 0;
    uint16_t tail = 1;

    memset(permutation_pdb, UCHAR_MAX, sizeof permutation_pdb);
    permutation_pdb[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        uint8_t face;
        for (face = 0; face < CUBE_FACES; ++face) {
            uint16_t there = here;
            uint8_t turn;
            for (turn = 0; turn < 3; ++turn) {
                there = permutation_turn[face][there];
                if (permutation_pdb[there] == UCHAR_MAX) {
                    permutation_pdb[there] =
                        (uint8_t) (permutation_pdb[here] + 1U);
                    queue[tail++] = there;
                }
            }
        }
    }
}

static void build_orientation_pdb(void)
{
    uint16_t queue[CUBE_ORIENTATIONS];
    uint16_t head = 0;
    uint16_t tail = 1;

    memset(orientation_pdb, UCHAR_MAX, sizeof orientation_pdb);
    orientation_pdb[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        uint8_t face;
        for (face = 0; face < CUBE_FACES; ++face) {
            uint16_t there = here;
            uint8_t turn;
            for (turn = 0; turn < 3; ++turn) {
                there = orientation_turn[face][there];
                if (orientation_pdb[there] == UCHAR_MAX) {
                    orientation_pdb[there] =
                        (uint8_t) (orientation_pdb[here] + 1U);
                    queue[tail++] = there;
                }
            }
        }
    }
}

static int write_u8_array(FILE *output, const char *name,
                          const uint8_t *values, size_t count)
{
    size_t i;
    if (fprintf(output, "const uint8_t %s[%lu] = {\n", name,
                (unsigned long) count) < 0)
        return 0;
    for (i = 0; i < count; ++i) {
        if (i % 24U == 0 && fputs("    ", output) == EOF)
            return 0;
        if (fprintf(output, "%u%s", values[i], i + 1U == count ? "" : ",") <
            0)
            return 0;
        if ((i + 1U) % 24U == 0 || i + 1U == count) {
            if (fputc('\n', output) == EOF)
                return 0;
        } else if (fputc(' ', output) == EOF) {
            return 0;
        }
    }
    return fputs("};\n\n", output) != EOF;
}

static int write_u16_array(FILE *output, const char *name,
                           const uint16_t *values, size_t count)
{
    size_t i;
    if (fprintf(output, "const uint16_t %s[%lu] = {\n", name,
                (unsigned long) count) < 0)
        return 0;
    for (i = 0; i < count; ++i) {
        if (i % 16U == 0 && fputs("    ", output) == EOF)
            return 0;
        if (fprintf(output, "%u%s", values[i], i + 1U == count ? "" : ",") <
            0)
            return 0;
        if ((i + 1U) % 16U == 0 || i + 1U == count) {
            if (fputc('\n', output) == EOF)
                return 0;
        } else if (fputc(' ', output) == EOF) {
            return 0;
        }
    }
    return fputs("};\n\n", output) != EOF;
}

static int write_tables(const char *path)
{
    static const char *const face_names[CUBE_FACES] = {"r", "b", "d"};
    FILE *output = fopen(path, "w");
    uint8_t face;
    int ok = output != NULL;

    if (!ok)
        return 0;
    ok = fputs("/* Generated by tools/generate_idastar_tables.c. */\n"
               "#include \"idastar_tables.h\"\n\n",
               output) != EOF;
    if (ok)
        ok = write_u8_array(output, "idastar_permutation_pdb",
                            permutation_pdb, CUBE_PERMUTATIONS);
    if (ok)
        ok = write_u8_array(output, "idastar_orientation_pdb",
                            orientation_pdb, CUBE_ORIENTATIONS);
    for (face = 0; ok && face < CUBE_FACES; ++face) {
        char name[64];
        if (snprintf(name, sizeof name, "idastar_permutation_turn_%s",
                     face_names[face]) < 0)
            ok = 0;
        else
            ok = write_u16_array(output, name, permutation_turn[face],
                                 CUBE_PERMUTATIONS);
    }
    for (face = 0; ok && face < CUBE_FACES; ++face) {
        char name[64];
        if (snprintf(name, sizeof name, "idastar_orientation_turn_%s",
                     face_names[face]) < 0)
            ok = 0;
        else
            ok = write_u16_array(output, name, orientation_turn[face],
                                 CUBE_ORIENTATIONS);
    }
    if (fclose(output) != 0)
        ok = 0;
    return ok;
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s OUTPUT.c\n", argv[0]);
        return 2;
    }
    build_quarter_turn_tables();
    build_permutation_pdb();
    build_orientation_pdb();
    if (!write_tables(argv[1])) {
        fprintf(stderr, "could not write %s\n", argv[1]);
        return 1;
    }
    return 0;
}
